USEMODULE += remote-common

# define the default port depending on the host OS
PORT_LINUX  ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

include $(RIOTBOARD)/remote-common/Makefile.include

#CC2538 and CC1200
GNRC_NETIF_NUMOF = 2
