ifneq (,$(filter gnrc_netdev_default,$(USEMODULE)))
    USEMODULE += netif
    USEMODULE += cc2538_rf
    #USEMODULE += cc1200
    USEMODULE += xtimer
    USEMODULE += gnrc_netdev2
    USEMODULE += netdev2_ieee802154
endif
ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif
